// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmcdfoawiixniqfmxyhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptY2Rmb2F3aWl4bmlxZm14eWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDQ0NjUsImV4cCI6MjA2MzU4MDQ2NX0.yP-vYYSKSPlrA3cKSVrXuOAZ-kub3NB9va3XV2uRh5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);